In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('amazon_product.csv')

In [10]:
df.head()

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN

In [11]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         64 non-null     object
 1   product_title                64 non-null     object
 2   product_price                64 non-null     object
 3   product_original_price       27 non-null     object
 4   currency                     64 non-null     object
 5   product_star_rating          54 non-null     float64
 6   product_num_ratings          64 non-null     int64
 7   product_url                  64 non-null     object
 8   product_photo                64 non-null     object
 9   product_num_offers           64 non-null     int64
 10  product_minimum_offer_price  64 non-null     object
 11  is_best_seller               64 non-null     bool
 12  is_amazon_choice             64 non-null     bool
 13  is_prime                     64 non-null     bool
 14  climate_pledge_friendly      64 non-null     bool
 15  sales_volume                 61 non-null     object
 16  delivery                     63 non-null     object
 17  has_variations               64 non-null     bool
 18  product_availability         1 non-null      object
 19  unit_price                   5 non-null      object
 20  unit_count                   5 non-null      float64
dtypes: bool(5), float64(2), int64(2), object(12)
memory usage: 8.4+ KB

"""
# Data Cleaning Steps:
- Check and remove redundant/unnecessary columns.
- Rename columns if needed.
- Check for and remove duplicate rows.
- Handle missing (NaN) values.
- Check and fix incorrect data types.
- Check for inconsistent or invalid values.
- Apply necessary data transformations.
"""

In [14]:
df.shape

(64, 21)

In [15]:
df.duplicated().sum()

0

In [16]:
df.isna().sum()

asin                            0
product_title                   0
product_price                   0
product_original_price         37
currency                        0
product_star_rating            10
product_num_ratings             0
product_url                     0
product_photo                   0
product_num_offers              0
product_minimum_offer_price     0
is_best_seller                  0
is_amazon_choice                0
is_prime                        0
climate_pledge_friendly         0
sales_volume                    3
delivery                        1
has_variations                  0
product_availability           63
unit_price                     59
unit_count                     59
dtype: int64

In [17]:
df.columns

Index(['asin', 'product_title', 'product_price', 'product_original_price',
       'currency', 'product_star_rating', 'product_num_ratings', 'product_url',
       'product_photo', 'product_num_offers', 'product_minimum_offer_price',
       'is_best_seller', 'is_amazon_choice', 'is_prime',
       'climate_pledge_friendly', 'sales_volume', 'delivery', 'has_variations',
       'product_availability', 'unit_price', 'unit_count'],
      dtype='object')

In [18]:
cols_drop = ['product_original_price' , 'product_availability' , 'unit_price' , 'unit_count']
df.drop(cols_drop, axis=1, inplace=True)
df.head()

,asin,product_title,product_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,10,$64.89,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True
1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,8,$145.87,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False
2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,1,$49.88,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False
3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,30,$289.99,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True
4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,2,$150.09,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True

In [19]:
df.dropna(inplace=True)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 63
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         53 non-null     object
 1   product_title                53 non-null     object
 2   product_price                53 non-null     object
 3   currency                     53 non-null     object
 4   product_star_rating          53 non-null     float64
 5   product_num_ratings          53 non-null     int64
 6   product_url                  53 non-null     object
 7   product_photo                53 non-null     object
 8   product_num_offers           53 non-null     int64
 9   product_minimum_offer_price  53 non-null     object
 10  is_best_seller               53 non-null     bool
 11  is_amazon_choice             53 non-null     bool
 12  is_prime                     53 non-null     bool
 13  climate_pledge_friendly      53 non-null     bool
 14  sales_volume                 53 non-null     object
 15  delivery                     53 non-null     object
 16  has_variations               53 non-null     bool
dtypes: bool(5), float64(1), int64(2), object(9)
memory usage: 5.6+ KB

In [23]:
df.duplicated().sum()

0

In [24]:
bool_cols = df.select_dtypes(include='bool').columns

df[bool_cols] = df[bool_cols].map(lambda x: 1 if x else 0)

In [25]:
df.head()

,asin,product_title,product_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,10,$64.89,0,0,1,0,6K+ bought in past month,"FREE delivery Tue, Aug 6",1
1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,8,$145.87,0,0,1,0,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",0
2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,1,$49.88,0,0,1,0,2K+ bought in past month,"FREE delivery Tue, Aug 6",0
3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,30,$289.99,0,0,0,0,10K+ bought in past month,FREE delivery Aug 6 - 8,1
4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,2,$150.09,0,0,1,1,3K+ bought in past month,"FREE delivery Tue, Aug 6",1

In [26]:
# Remove unnecessary columns
df.drop(columns=['product_photo', 'product_url'], inplace=True)

# Convert price columns to numeric
df['product_price'] = df['product_price'].str.replace('$', '').astype(float)

df['product_minimum_offer_price'] = (
    df['product_minimum_offer_price']
    .str.replace('$', '')
    .astype(float)
)

# Check currency
df['currency'].value_counts()

currency
USD    53
Name: count, dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53 entries, 0 to 63
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         53 non-null     object
 1   product_title                53 non-null     object
 2   product_price                53 non-null     float64
 3   currency                     53 non-null     object
 4   product_star_rating          53 non-null     float64
 5   product_num_ratings          53 non-null     int64
 6   product_num_offers           53 non-null     int64
 7   product_minimum_offer_price  53 non-null     float64
 8   is_best_seller               53 non-null     int64
 9   is_amazon_choice             53 non-null     int64
 10  is_prime                     53 non-null     int64
 11  climate_pledge_friendly      53 non-null     int64
 12  sales_volume                 53 non-null     object
 13  delivery                     53 non-null     object
 14  has_variations               53 non-null     int64
dtypes: float64(3), int64(7), object(5)
memory usage: 6.6+ KB

In [28]:
df.nunique()

asin                           53
product_title                  53
product_price                  36
currency                        1
product_star_rating            15
product_num_ratings            51
product_num_offers             13
product_minimum_offer_price    39
is_best_seller                  2
is_amazon_choice                2
is_prime                        2
climate_pledge_friendly         2
sales_volume                   30
delivery                       15
has_variations                  2
dtype: int64

In [29]:
df.columns = df.columns.str.capitalize()
df.columns

Index(['Asin', 'Product_title', 'Product_price', 'Currency',
       'Product_star_rating', 'Product_num_ratings', 'Product_num_offers',
       'Product_minimum_offer_price', 'Is_best_seller', 'Is_amazon_choice',
       'Is_prime', 'Climate_pledge_friendly', 'Sales_volume', 'Delivery',
       'Has_variations'],
      dtype='object')

In [30]:
df.to_csv('amazon_product_cleaned.csv')
df.to_csv('amazon_product_cleaned.csv', index=False)