In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('zomato.csv')

In [3]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [5]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [6]:
df.isnull().sum()

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

In [8]:
df_to_drop = ['url', 'address' , 'votes' , 'location', 'rest_type' ,'phone','cuisines', 'reviews_list', 'menu_item', 'listed_in(type)', 'listed_in(city)']

In [9]:
df.drop(columns = df_to_drop , inplace = True)

In [10]:
df.shape

(51717, 6)

In [11]:
# Filter data
df.rename(columns = {
    'name' : 'name1',
    'online_order' : 'Online_order'} , inplace = True)

In [12]:
df.columns

Index(['name1', 'Online_order', 'book_table', 'rate', 'dish_liked',
       'approx_cost(for two people)'],
      dtype='object')

In [13]:
new_cols = []
for i in df.columns :
    new_cols.append(i.capitalize())

In [14]:
new_cols

['Name1',
 'Online_order',
 'Book_table',
 'Rate',
 'Dish_liked',
 'Approx_cost(for two people)']

In [15]:
df.columns = new_cols

In [16]:
df.columns

Index(['Name1', 'Online_order', 'Book_table', 'Rate', 'Dish_liked',
       'Approx_cost(for two people)'],
      dtype='object')

In [31]:
df.head()

,Name1,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600

In [33]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
51712     True
51713     True
51714    False
51715     True
51716     True
Length: 51717, dtype: bool

In [35]:
df = df.drop_duplicates()

In [37]:
df.duplicated().value_counts()

False    18909
Name: count, dtype: int64

In [39]:
df.duplicated().sum()

0

In [41]:
df.isna()

,Name1,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
51631,False,False,False,False,True,False
51632,False,False,False,False,True,False
51641,False,False,False,False,True,True
51677,False,False,False,False,False,False
51714,False,False,False,True,True,False

In [43]:
df.isna().sum()

Name1                              0
Online_order                       0
Book_table                         0
Rate                            2418
Dish_liked                     10587
Approx_cost(for two people)      140
dtype: int64

In [53]:
df.dropna(inplace = True)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8250 entries, 0 to 51677
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Name1                        8250 non-null   object
 1   Online_order                 8250 non-null   object
 2   Book_table                   8250 non-null   object
 3   Rate                         8250 non-null   object
 4   Dish_liked                   8250 non-null   object
 5   Approx_cost(for two people)  8250 non-null   object
dtypes: object(6)
memory usage: 451.2+ KB

In [57]:
df.isna().sum()

Name1                          0
Online_order                   0
Book_table                     0
Rate                           0
Dish_liked                     0
Approx_cost(for two people)    0
dtype: int64

In [59]:
df.reset_index(inplace= True)

In [61]:
df.drop(columns = 'index' , inplace = True)

In [63]:
df.head()

,Name1,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600

In [75]:
df['Rate'].str.replace(' ' , '')

0       4.1/5
1       4.1/5
2       3.8/5
3       3.7/5
4       3.8/5
        ...
8245    2.5/5
8246    3.6/5
8247    3.8/5
8248    4.2/5
8249    2.5/5
Name: Rate, Length: 8250, dtype: object

In [77]:
df['Rate'].str.replace('/', ' out of ')

0        4.1 out of 5
1        4.1 out of 5
2        3.8 out of 5
3        3.7 out of 5
4        3.8 out of 5
            ...
8245    2.5  out of 5
8246    3.6  out of 5
8247    3.8  out of 5
8248    4.2  out of 5
8249    2.5  out of 5
Name: Rate, Length: 8250, dtype: object

In [83]:
df['Online_order'] = df['Online_order'].apply(lambda x:1 if x =="Yes" else 0)

In [85]:
df

,Name1,Online_order,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,1,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,1,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,1,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7/5,Masala Dosa,300
4,Grand Village,0,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,0,No,2.5 /5,Manchow Soup,800
8246,Breakfast House,0,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,1,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,0,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,0,No,2.5 /5,"Biryani, Andhra Meal",800

In [87]:
df.to_csv('Cleaned_Zomato.csv')

In [ ]:
df.to_csv('Cleaned_Zomato.csv' , in)